// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import slack "github.com/nlopes/slack"

// MessageHelper is an autogenerated mock type for the MessageHelper type
type MessageHelper struct {
	mock.Mock
}

// Post provides a mock function with given fields: ctx, channelID, text, options
func (_m *MessageHelper) Post(ctx context.Context, channelID string, text string, options ...slack.MsgOption) (string, string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, channelID, text)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...slack.MsgOption) string); ok {
		r0 = rf(ctx, channelID, text, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...slack.MsgOption) string); ok {
		r1 = rf(ctx, channelID, text, options...)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, string, ...slack.MsgOption) error); ok {
		r2 = rf(ctx, channelID, text, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
